stateDiagram-v2
  [*] --> LoggedOut

  LoggedOut --> Browsing
  LoggedOut --> Login
  LoggedOut --> Register_account

  Login --> LoggedIn
  Register_account --> LoggedIn
  LoggedIn --> Browsing
  LoggedIn --> LoggedOut: Logout

  Browsing --> CartCreated: Select activity session
  CartCreated --> Checkout
  CartCreated --> Cancelled
  CartCreated --> Login: Requires login
  CartCreated --> Register_account: Requires account

  Checkout --> Cart_Pending
  Cart_Pending --> Waiting_payment: Proceed to payment
  Waiting_payment --> Payment_success
  Payment_success --> Cart_Confirmed

  Cart_Pending --> Cart_Cancelled: User cancels
  Cart_Confirmed --> Cart_Refunded: Refund

  Cart_Confirmed --> [*]
  Cart_Cancelled --> [*]
  Cart_Refunded --> [*]

  state Cart_Confirmed {
    [*] --> Order_Created
    Order_Created --> Order_Confirmed: Payment validated
    Order_Created --> Order_Cancelled: Cart cancelled
    Order_Confirmed --> Order_Refunded: Refund
    Order_Confirmed --> [*]
    Order_Cancelled --> [*]
    Order_Refunded --> [*]
  }
