FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY vite-frontend/package*.json ./vite-frontend/
RUN npm install --workspace=vite-frontend --ignore-scripts

COPY vite-frontend/ ./vite-frontend/
RUN npm run build --workspace=vite-frontend

# ---

FROM nginx:alpine AS runner

COPY --from=builder /app/vite-frontend/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
